/* DONT READ DIRECTLY FROM THIS FILE, MAKE A FUNCTION IN UTILS.JS TO GET THESE VALUES! */
/* DONT READ DIRECTLY FROM THIS FILE, MAKE A FUNCTION IN UTILS.JS TO GET THESE VALUES! */
/* DONT READ DIRECTLY FROM THIS FILE, MAKE A FUNCTION IN UTILS.JS TO GET THESE VALUES! */
/* DONT READ DIRECTLY FROM THIS FILE, MAKE A FUNCTION IN UTILS.JS TO GET THESE VALUES! */
/* DONT READ DIRECTLY FROM THIS FILE, MAKE A FUNCTION IN UTILS.JS TO GET THESE VALUES! */
/* DONT READ DIRECTLY FROM THIS FILE, MAKE A FUNCTION IN UTILS.JS TO GET THESE VALUES! */
module.exports = {
  dev: {
    port: 3000
  },
  prod: {
    port: 3000
  }
}

/* DONT FORGET TO UPDATE RELEVANT FIELDS IN THE MANIFEST */
/* DONT FORGET TO UPDATE RELEVANT FIELDS IN THE MANIFEST */
/* DONT FORGET TO UPDATE RELEVANT FIELDS IN THE MANIFEST */
/* DONT FORGET TO UPDATE RELEVANT FIELDS IN THE MANIFEST */
/* DONT FORGET TO UPDATE RELEVANT FIELDS IN THE MANIFEST */
/* DONT FORGET TO UPDATE RELEVANT FIELDS IN THE MANIFEST */